# Generated by Django 5.0 on 2024-12-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osSite', '0004_teacher_grade_teacher_delete_osstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.PositiveIntegerField(verbose_name='Գնահատական'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Առարկա'),
        ),
    ]
