# Generated by Django 5.0 on 2024-12-19 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osSite', '0008_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
