# Generated by Django 5.0 on 2025-01-25 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osSite', '0010_lessonschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testitem', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
