# Generated by Django 5.0 on 2025-01-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osSite', '0011_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
